### ISSUE TITLE
double page number

### ISSUE THREAD

**Issue by JLuc** [HOST-Oman/scribus#237] opened 2016-12-02 11:20 UTC
When importing a non-CTL 153 document , page number get displayed twice in a row.
Instead of 5 one sees 55

AMOF strangest is that in the SLA, there is
```
  <var name="pgno" CPARENT="Pagination"/>
  <var name="pgno" CPARENT="Pagination"/>
```

These double pgno were allready there in original file, but were not displayed, when they are with CTL.

So however the issue might be not in CTL but in non-CTL, CTL might smartly correct these double when importing ?

I could create a simple test document that reproduces the issue 
- with Version de Scribus 1.5.2.svn SVN : 21106 the double page number appears as single
- with CTL Scribus Version 1.5.3.svn 17 November 2016, it appears as it should = double

See uploaded file (rename without .txt)

[double page number.sla.txt](https://github.com/HOST-Oman/scribus/files/627017/double.page.number.sla.txt)

**Comment by Fahad-Alsaidi** [comment] 2016-12-02 13:25
if CTL does the correct thing, this means that there is a bug in Scribus 1.5.2.svn and get fixed in CTL. The right thing to do is delete the second page number.

**Comment by aoloe** [comment] 2016-12-02 16:24
older versions of scribus needed two # for page numbers between 10 and 99...

maybe this fact might help sorting the issue...

**Comment by Fahad-Alsaidi** [comment] 2016-12-04 07:26
not a bug.

**Closed as completed by Fahad-Alsaidi** 2016-12-04 07:26 UTC
