### ISSUE TITLE
Bottom / Middle vertical alignment of text in a text frame is not working properly

### ISSUE THREAD

**Issue by dkgh707** [HOST-Oman/scribus#219] opened 2016-09-16 03:54 UTC
I have discovered a problem when attempting to adjust the alignment of text vertically within a text box.  If the "Middle" or "Bottom" vertical alignment setting is chosen from the **Columns & Text Distances** tab, the text will be placed too low in the text box.  I have not yet located the root cause of the problem, but I have traced the issue to an incorrect hAdjust value on line 2976 of pageitem_textframe.cpp.  The function textLayout.box()->naturalHeight() is returning a value of zero instead of the proper height of the text.  I think this problem was introduced in one of the commits that occurred between mid and late July.

Thanks,
Dave

**Comment by Fahad-Alsaidi** [comment] 2016-09-17 00:29
Thanks Dave for reporting & analysis. Since I am busy these days with other
things, I appreciate if you can send a pull request.

On 16 Sep 2016 7:54 a.m., "dkgh707" notifications@github.com wrote:

I have discovered a problem when attempting to adjust the alignment of text
vertically within a text box. If the "Middle" or "Bottom" vertical
alignment setting is chosen from the _Columns & Text Distances_ tab, the
text will be placed too low in the text box. I have not yet located the
root cause of the problem, but I have traced the issue to an incorrect
hAdjust value on line 2976 of pageitem_textframe.cpp. The function
textLayout.box()->naturalHeight() is returning a value of zero instead of
the proper height of the text. I think this problem was introduced in one
of the commits that occurred between mid and late July.

Thanks,
Dave

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/HOST-Oman/scribus/issues/219, or mute the thread

**Comment by dkgh707** [comment] 2016-09-18 21:55
I'd be happy to make a pull request, but I am unfamiliar with how the project is structured.  Since I do not have permissions to create a branch for this issue, I am not sure what exactly you want me to do.

Thanks,
Dave

**Comment by Fahad-Alsaidi** [comment] 2016-09-19 01:46
The easiest way is to fix the problem in your computer then make a patch
and attach here.

**Comment by Fahad-Alsaidi** [comment] 2016-10-22 09:15
please test now. It should be fixed by ebbc3a928258d77cc975b09f53a69c20e49f7cce

**Comment by Fahad-Alsaidi** [comment] 2016-10-30 06:16
closing this now, please reopen it if you have a problem.

**Closed as completed by Fahad-Alsaidi** 2016-10-30 06:16 UTC
