### ISSUE TITLE
pending issues that are blocking 1.5.2 release

### ISSUE THREAD

**Issue by luzpaz** [HOST-Oman/scribus#147] opened 2016-04-13 19:55 UTC
- [x] [13871](https://bugs.scribus.net/view.php?id=13871) **If paragraph contains DropCaps and pressed Enter, before Space --> content disappears**
- [x] [13947](https://bugs.scribus.net/view.php?id=13947) **Endless selection**
- [x] [13881](https://bugs.scribus.net/view.php?id=13881) **First line text selection is inaccurate if "Align to Baseline Grid" is enabled**
- [x] [13894](https://bugs.scribus.net/view.php?id=13894) **"Paragraph Effects" for numbered (or un-numbered) lists get removed when creating a new line or pressing backspace**
- [x] [13938](https://bugs.scribus.net/view.php?id=13938) **Orphans and widows line management leads to blank text frames depending on the size of the frame** (possibly)
- [x] [13893](https://bugs.scribus.net/view.php?id=13893) **Some text wrapping is broken / renders differently when opening a Scribus 1.4.x file with Scribus 1.5.2**
- [x] [13948](https://bugs.scribus.net/view.php?id=13948) **It's hard select text, if "Space Above" enlarged!**

@khaledhosny & @Fahad-Alsaidi 
Craig is asking about these text bugs. They are getting in the way of 1.5.2 being released. Before CTL can be merged all boxes regressions need to be fixed. There is even talk that once boxes bugs get fixed 1.5.2 will be released and then 1.5.3 will be when CTL gets merged. 

CTL could be merged in to 1.5.2 but the team thinks that there should be separation between the 2 major code changes.

**Comment by luzpaz** [comment] 2016-04-13 20:20
Addendum: 
1. such a release does not need to delay CTL
2. its open for discussion since no discussion has occurred so far on the mailing list

**Comment by luzpaz** [comment] 2016-04-15 13:55
FYI, a fix for [13881](https://bugs.scribus.net/view.php?id=13881) was committed in 0b0aac9f97cef0cd416559ec062592cf6055b34c by jghali. 

Edit:
and [13948](https://bugs.scribus.net/view.php?id=13948)

**Comment by khaledhosny** [comment] 2016-04-15 14:06
#129 should fix 13871, but I don’t feel comfortable merging this without understanding what is going on. If one of the developers wants to look into it, that would be great.

Related to this, we need a list of all boxes related issues fixed on TRUNK and someone to test them against CTL branch and report what is not fixed there. The same for the open boxes issues, some of them might already be fixed in CTL branch.

**Comment by khaledhosny** [comment] 2016-04-15 14:07
For example 13881 is already fixed in CTL branch.

**Comment by Fahad-Alsaidi** [comment] 2016-04-15 18:01
#151 should fix [#13938](https://bugs.scribus.net/view.php?id=13938). @luzpaz please test.

**Comment by Fahad-Alsaidi** [comment] 2016-04-17 05:37
I can't reproduce [#13894](https://bugs.scribus.net/view.php?id=13894)  in CTL branch.

**Comment by Fahad-Alsaidi** [comment] 2016-04-18 04:18
All of these bugs are fixed, closed, or not related to boxes model. So should we close this bug?

**Comment by khaledhosny** [comment] 2016-04-25 00:05
Is there anything actionable remaining here?

**Comment by luzpaz** [comment] 2016-04-25 14:55
http://lists.scribus.net/pipermail/scribus-dev/2016-April/003064.html

**Closed as completed** 2016-04-26 12:50 UTC
